name: quran_stemmer
description: The Quran Stemmer is an implementation of the ISRI Stemmer algorithm for the Arabic language. The stemmer is specifically designed to process Quranic Arabic text by reducing words to their root forms, enabling various text analysis tasks such as information retrieval, text mining, and natural language processing.
version: 1.0.1
repository: https://github.com/h-bougattaya/quran_stemmer

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  dartarabic: ^0.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
